development:
  adapter: postgresql
  encoding: unicode
  database: ask_expert_dev
  pool: 5
  host: localhost
  port: 5432
  username: ask_expert
  password: ask_expert

test:
  adapter: postgresql
  encoding: unicode
  database: ask_expert_test
  pool: 5
  host: localhost
  port: 5432
  username: ask_expert
  password: ask_expert
